# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1023)], verbose_name='personal description'),
        ),
    ]
