# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:41
from __future__ import unicode_literals

import biohub.utils.db
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('biobrick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=15)),
                ('params', biohub.utils.db.PackedField()),
                ('acttime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('digest', models.TextField(blank=True)),
                ('files', models.ManyToManyField(default=None, to='files.File')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_fetched', models.DateTimeField(default=None, null=True, verbose_name='last updated')),
                ('pub_time', models.DateField(default=datetime.date.today, verbose_name='publish time')),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_set', to=settings.AUTH_USER_MODEL)),
                ('brick', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='biobrick.BiobrickMeta')),
                ('content', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Article')),
                ('voted_users', models.ManyToManyField(related_name='experiences_voted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pub_time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='publish time')),
                ('is_visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='forum.Experience')),
            ],
            options={
                'ordering': ['pub_time'],
            },
        ),
    ]
