# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_part', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('designer', models.CharField(default='', max_length=100)),
                ('group_name', models.CharField(default='', max_length=100)),
                ('part_type', models.CharField(default='', max_length=50)),
                ('part_status', models.CharField(choices=[('Released', 'Released'), ('Released HQ', 'Released HQ'), ('Not Released', 'Not Released'), ('Discontinued', 'Discontinued')], default='Not Released', max_length=15)),
                ('sample_status', models.CharField(choices=[('Sample in Stock', 'Sample in Stock'), ("It's complicated", "It's complicated"), ('Not in Stock', 'Not in Stock'), ('Informational', 'Informational')], default='Sample in Stock', max_length=20)),
                ('experience_status', models.CharField(choices=[('works', 'works'), ('issues', 'issues'), ('fails', 'fails')], default='works', max_length=8)),
                ('use_num', models.PositiveIntegerField(default=0)),
                ('twin_num', models.PositiveIntegerField(default=0)),
                ('assembly_compatibility', models.CharField(default='', max_length=40)),
                ('parameters', models.TextField(default='')),
                ('categories', models.TextField(default='')),
                ('sequence_a', models.TextField(default='')),
                ('sequence_b', models.TextField(default='')),
                ('used_by', models.TextField(blank=True, default='')),
                ('sub_parts', models.TextField(blank=True, default='')),
                ('document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Article')),
                ('followers', models.ManyToManyField(related_name='bricks_from_follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, default='', max_length=1000)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('pub_time', models.DateField(auto_now_add=True, verbose_name='publish date')),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('rate_num', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brick', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Brick')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pointer', models.FileField(upload_to='upload')),
                ('description', models.TextField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('pub_time', models.DateField(auto_now_add=True, verbose_name='publish date')),
                ('up_vote_num', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Experience')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(to='forum.File'),
        ),
    ]
