# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='brick',
            name='assembly_compatibility',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
