# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='user',
            new_name='users',
        ),
    ]
