# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170722_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='reply_to',
        ),
    ]
