# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 04:45
from __future__ import unicode_literals

import biohub.utils.db
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170909_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='assembly_compatibility',
            field=biohub.utils.db.PackedField(default='', max_length=100),
        ),
    ]
