# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170803_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
