# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170730_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
