# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170919_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='brick_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
