# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20170803_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brick',
            name='followers',
        ),
        migrations.AddField(
            model_name='brick',
            name='star_users',
            field=models.ManyToManyField(related_name='bricks_starred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brick',
            name='watch_users',
            field=models.ManyToManyField(related_name='bricks_watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
