# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170722_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='part',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Part'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='studio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Studio'),
        ),
    ]
