# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170722_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_comment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
