# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170808_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='experience_status',
            field=models.CharField(default='works', max_length=30),
        ),
        migrations.AlterField(
            model_name='brick',
            name='part_status',
            field=models.CharField(default='Not Released', max_length=30),
        ),
        migrations.AlterField(
            model_name='brick',
            name='sample_status',
            field=models.CharField(default='Sample in Stock', max_length=30),
        ),
    ]
