# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170911_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='digest',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
    ]
