# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_post_is_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispart', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sequence_a', models.TextField()),
                ('sequence_b', models.TextField()),
                ('type', models.CharField(max_length=250)),
                ('external_parts', models.TextField(blank=True, default='')),
                ('document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brick_from_doc', to='forum.Article')),
                ('followers', models.ManyToManyField(related_name='bricks_from_follower', to=settings.AUTH_USER_MODEL)),
                ('internal_part_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_parts', to='forum.Brick')),
                ('lab_record', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brick_from_record', to='forum.Article')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricks_from_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepointer', models.FileField(upload_to='upload')),
                ('description', models.TextField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('granted', models.BooleanField(default=False)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('accept_time', models.DateTimeField()),
                ('brick', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Brick')),
                ('commit_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='part',
        ),
        migrations.AddField(
            model_name='studio',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studios_from_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='users',
            field=models.ManyToManyField(related_name='studios_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(to='forum.File'),
        ),
        migrations.AddField(
            model_name='thread',
            name='brick',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Brick'),
        ),
    ]
