# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170801_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqfeature',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
