# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_seqfeature_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brick',
            name='dna_position',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='is_part',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='used_by',
        ),
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(default=None, to='files.File'),
        ),
        migrations.AlterField(
            model_name='brick',
            name='sub_parts',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
