# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0008_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expLink', models.CharField(blank=True, default='', max_length=100)),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('partName', models.CharField(default='', max_length=15)),
                ('intro', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='partName',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='score',
        ),
        migrations.AddField(
            model_name='activity',
            name='params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.ActivityParam'),
        ),
    ]
