# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_activityparam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='acttime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
