# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_activity_acttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='designer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='brick',
            name='experience_status',
            field=models.CharField(default='works', max_length=50),
        ),
        migrations.AlterField(
            model_name='brick',
            name='group_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='brick',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='brick',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='brick',
            name='part_status',
            field=models.CharField(default='Not Released', max_length=50),
        ),
        migrations.AlterField(
            model_name='brick',
            name='part_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='brick',
            name='sample_status',
            field=models.CharField(default='Sample in Stock', max_length=50),
        ),
    ]
