# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0012_auto_20170813_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='star_users',
            field=models.ManyToManyField(related_name='bricks_starred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brick',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
