# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20170906_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='brick',
            name='part_type',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seqfeature',
            name='feature_type',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
    ]
