# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abacus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=255)),
                ('upload_file', models.FileField(upload_to='upload/')),
                ('download_file', models.FileField(upload_to='')),
                ('status', models.IntegerField()),
            ],
        ),
    ]
