# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abacus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abacus',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='abacus', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abacus',
            name='upload_file',
            field=models.FileField(upload_to='biohub/abacus//storage/upload/'),
        ),
    ]
