# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abacus', '0002_auto_20170720_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abacus',
            name='user',
        ),
    ]
