# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biobrick',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('ok', models.NullBooleanField(default=True)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('part_type', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('owning_group_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('dominant', models.NullBooleanField(default=False)),
                ('informational', models.NullBooleanField(default=False)),
                ('discontinued', models.IntegerField(default=0, null=True)),
                ('part_status', models.CharField(max_length=40, null=True)),
                ('sample_status', models.CharField(max_length=40, null=True)),
                ('p_status_cache', models.CharField(max_length=1000, null=True)),
                ('s_status_cache', models.CharField(max_length=1000, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('m_datetime', models.DateTimeField(blank=True, null=True)),
                ('m_user_id', models.IntegerField(default=0, null=True)),
                ('uses', models.IntegerField(default=-1, null=True)),
                ('doc_size', models.IntegerField(default=0, null=True)),
                ('works', models.CharField(max_length=10)),
                ('favorite', models.IntegerField(default=0, null=True)),
                ('specified_u_list', models.TextField(blank=True, null=True)),
                ('deep_u_list', models.TextField(blank=True, null=True)),
                ('deep_count', models.IntegerField(blank=True, null=True)),
                ('ps_string', models.TextField(blank=True, null=True)),
                ('scars', models.CharField(default='10', max_length=20, null=True)),
                ('default_scars', models.CharField(default='10', max_length=20)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('group_u_list', models.TextField(blank=True, null=True)),
                ('has_barcode', models.NullBooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
                ('nickname', models.CharField(max_length=10, null=True)),
                ('categories', models.CharField(blank=True, max_length=500, null=True)),
                ('sequence', models.TextField()),
                ('sequence_sha1', models.BinaryField(max_length=20, null=True)),
                ('sequence_update', models.IntegerField(default=5, null=True)),
                ('seq_edit_cache', models.TextField(blank=True, null=True)),
                ('review_result', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('review_total', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('sequence_length', models.IntegerField(default=0, null=True)),
                ('temp_1', models.IntegerField(blank=True, null=True)),
                ('temp_2', models.IntegerField(blank=True, null=True)),
                ('temp_3', models.IntegerField(blank=True, null=True)),
                ('temp4', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_type', models.CharField(blank=True, max_length=200, null=True)),
                ('start_pos', models.IntegerField(blank=True, null=True)),
                ('end_pos', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('label2', models.CharField(blank=True, max_length=200, null=True)),
                ('mark', models.IntegerField(default=0, null=True)),
                ('old', models.IntegerField(default=0, null=True)),
                ('reverse', models.IntegerField(default=0, null=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='biobrick.Biobrick')),
            ],
            options={
                'db_table': 'parts_seq_features',
            },
        ),
    ]
