# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ..sql.creation.views_creation import migration_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biobrick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobrickmeta',
            name='document',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Article'),
        ),
        migrations.AddField(
            model_name='biobrickmeta',
            name='users_rated',
            field=models.ManyToManyField(related_name='bricks_rated', through='biobrick.RatedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biobrickmeta',
            name='users_starred',
            field=models.ManyToManyField(related_name='bricks_starred', through='biobrick.StarredUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biobrickmeta',
            name='users_watching',
            field=models.ManyToManyField(related_name='bricks_watching', through='biobrick.WatchingUser', to=settings.AUTH_USER_MODEL),
        ),
        migration_sql
    ]
