# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobrick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobrick',
            name='ac',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biobrick',
            name='ruler',
            field=models.TextField(null=True),
        ),
    ]
